[package]
name = "snowcap_ltl_parser"
version = "0.1.0"
authors = ["Tibor Schneider <tiborschneider@bluewin.ch>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
snowcap = {path = "../snowcap"}
syn = {version = "1.0", features = ["extra-traits", "full"]}
quote = "1.0"
proc-macro2 = "1.0"
